"""Add auto_query_enabled field to Customer

Revision ID: 0c7da162adf5
Revises: 528efb7777a8
Create Date: 2025-10-02 21:38:03.476288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7da162adf5'
down_revision = '528efb7777a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_query_enabled', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('auto_query_enabled')

    # ### end Alembic commands ###
